steps:
  - label: ":node: Lint"
    key: lint
    command:
      - npm ci
      - npm run lint
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml
  - label: ":cloudflare: Build"
    if: build.branch != pipeline.default_branch
    command:
      - npm ci
      - npm run build
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml
  - label: ":cloudflare: Build and deploy"
    key: deploy
    depends_on: lint
    if: build.branch == pipeline.default_branch
    command:
      - npm ci
      - npm run deploy
    env:
      VAULT_ROLE_ID: 703f9e62-1225-507b-ab21-9b762f8db482
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml
          env:
            - CLOUDFLARE_ACCOUNT_ID
            - CLOUDFLARE_API_TOKEN
