steps:
  - label: ":node: Lint"
    key: lint
    command:
      - npm ci
      - npm run lint
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml
  - label: ":cloudflare: Build and deploy"
    key: deploy
    depends_on: lint
    command:
      - npm ci
      - npm run deploy
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml
          env:
            - CLOUDFLARE_API_TOKEN
