#!/bin/bash

set -euo pipefail

if [[ "$BUILDKITE_STEP_KEY" == "deploy" ]]; then
    CLOUDFLARE_ACCOUNT_ID="$(vault kv get -field cloudflare_account_id buildkite/bandcamp-mini-embed)"
    export CLOUDFLARE_ACCOUNT_ID
    CLOUDFLARE_API_TOKEN="$(vault kv get -field cloudflare_api_token buildkite/bandcamp-mini-embed)"
    export CLOUDFLARE_API_TOKEN
fi
