name: Build and deploy to Cloudflare

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies, build Svelte embed and worker
        run: |
          npm ci
          npm run build:embed
          npm run build:worker
      - name: Deploy worker
        run: npm run deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
