name: Build and deploy client

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies, build Svelte embed and worker
        run: |
          nvm use
          npm ci
          npm run build
          npm i -g @cloudflare/wrangler
          wrangler build
      - name: Deploy worker
        run: wrangler publish
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
